### ISSUE TITLE
Cannot read property 'slice' of null when computing bounding box

### ISSUE THREAD

**Issue by aronfiechter** [wanadev/gltf-bounding-box#8]
I am using this to compute the bounding box of a `gltf` file, but an error happens. Here is the stack trace:
```
TypeError: Cannot read property 'slice' of null
    at Object._loadBufferView (.../gltf-bounding-box/dist/webpack:/src/gltf-reader.js:92:19)
    at Object._loadAccessor (.../gltf-bounding-box/dist/webpack:/src/gltf-reader.js:48:31)
    at .../gltf-bounding-box/dist/webpack:/src/gltf-reader.js:25:47
    at Array.forEach (<anonymous>)
    at loadPositions (.../gltf-bounding-box/dist/webpack:/src/gltf-reader.js:21:21)
    at .../gltf-bounding-box/dist/webpack:/src/gltf2-bounding-box.js:46:51
    at Array.reduce (<anonymous>)
    at Object.getMeshesTransformMatrices (.../gltf-bounding-box/dist/webpack:/src/gltf2-bounding-box.js:39:8)
    at Object.computeBoundings (.../gltf-bounding-box/dist/webpack:/src/gltf2-bounding-box.js:8:28)
    at Object.computeBoundings (.../gltf-bounding-box/dist/webpack:/src/index.js:23:33)
```

I am using `node` 8.15.0 on macOS 10.13.4

**Comment by aronfiechter** [comment]
(Cannot reproduce)
